// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL_6by3iBPsjjg7BGtu8q8aroZRq7z3C8',
    appId: '1:240922861367:web:ed918e1087a4a9790c84b2',
    messagingSenderId: '240922861367',
    projectId: 'mobile-assignment-db',
    authDomain: 'mobile-assignment-db.firebaseapp.com',
    storageBucket: 'mobile-assignment-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVftvAO7bgo1qD2Sh58XMi3he3SMqusPY',
    appId: '1:240922861367:android:f8f24e4cfe7b3cc90c84b2',
    messagingSenderId: '240922861367',
    projectId: 'mobile-assignment-db',
    storageBucket: 'mobile-assignment-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlhSF56uKaGkb0OCYhmgXzBalczvMWDI',
    appId: '1:240922861367:ios:f18bbccc5e0748d20c84b2',
    messagingSenderId: '240922861367',
    projectId: 'mobile-assignment-db',
    storageBucket: 'mobile-assignment-db.firebasestorage.app',
    iosBundleId: 'jau.sdn.bhd.mobileAppAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlhSF56uKaGkb0OCYhmgXzBalczvMWDI',
    appId: '1:240922861367:ios:f18bbccc5e0748d20c84b2',
    messagingSenderId: '240922861367',
    projectId: 'mobile-assignment-db',
    storageBucket: 'mobile-assignment-db.firebasestorage.app',
    iosBundleId: 'jau.sdn.bhd.mobileAppAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL_6by3iBPsjjg7BGtu8q8aroZRq7z3C8',
    appId: '1:240922861367:web:c0e56ccb58c8f5250c84b2',
    messagingSenderId: '240922861367',
    projectId: 'mobile-assignment-db',
    authDomain: 'mobile-assignment-db.firebaseapp.com',
    storageBucket: 'mobile-assignment-db.firebasestorage.app',
  );

}